services:
  web:
    build: .
    ports: ["8080:80"]
    volumes:
      - ./src:/var/www/html:cached
    depends_on: [db]
  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: app
      MYSQL_USER: app
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
